In [1]:
!ls

0.png  3.png	       Untitled1.ipynb	distrib.zip  params.py
1.png  4.png	       __pycache__	eval.py
2.png  Untitled.ipynb  distrib		leenet.ph


In [2]:
from PIL import Image
from IPython.display import display
import numpy as np

import torch
import torch.nn as nn
from torch.autograd import Function, Variable
from torch.nn.parameter import Parameter
from torchvision import datasets, transforms
import torch.nn.functional as F

In [3]:
NFEATURES=16*16
NHIDDEN=8*8
NCL=5
EPS = 0.00001

# not LeNet
class LeeNet(nn.Module):
    def __init__(self, nFeatures=NFEATURES, nHidden=NHIDDEN, nCl=NCL):
        super().__init__()
        self.fc1 = nn.Linear(nFeatures, nHidden)
        self.fc2 = nn.Linear(nHidden, nCl)
        
    def forward(self, x):
        nBatch = x.size(0)

        # Normal FC network.
        x = x.view(nBatch, -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.layer_norm(x, x.size()[1:], eps=1e-50)
        
        probs = F.softmax(x, dim=1) 
        
        return probs

In [4]:
model = LeeNet()
model.load_state_dict(torch.load("./leenet.ph"))

<All keys matched successfully>

In [5]:
model

LeeNet(
  (fc1): Linear(in_features=256, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=5, bias=True)
)

In [6]:
for param in model.parameters():
    param.requires_grad = True

In [7]:
im = Image.new('L', (16, 16), (128))

In [8]:
display(im)

In [9]:
im_np = np.asarray(im).reshape(1, NFEATURES) / 256
im_np

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5

In [10]:
im_tensor = torch.Tensor(im_np)
im_tensor.requires_grad = True
im_tensor

tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
         0.5000, 0.5000, 0.5

In [11]:
im_tensor.grad = None
model.zero_grad()
preds = model(im_tensor)
target = torch.empty([1], dtype=torch.long)
target[0] = 1
loss = nn.CrossEntropyLoss()
output = loss(preds, target)
output.backward()
output

/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py:145: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:104.)
  Variable._execution_engine.run_backward(


tensor(1.5843, grad_fn=<NllLossBackward>)

In [12]:
im_tensor = im_tensor - im_tensor.grad
im_tensor

tensor([[0.4840, 0.5024, 0.5076, 0.4929, 0.5118, 0.5018, 0.4755, 0.5197, 0.5313,
         0.5118, 0.4900, 0.5524, 0.4432, 0.4769, 0.4607, 0.4685, 0.4043, 0.4905,
         0.4742, 0.5461, 0.5727, 0.4363, 0.4767, 0.4839, 0.4906, 0.5387, 0.4519,
         0.5255, 0.5083, 0.4954, 0.5289, 0.4148, 0.4635, 0.4890, 0.4682, 0.5188,
         0.5421, 0.5007, 0.5283, 0.4658, 0.4977, 0.5336, 0.4901, 0.5218, 0.5264,
         0.4376, 0.5242, 0.5321, 0.4514, 0.5138, 0.4714, 0.5224, 0.5453, 0.4778,
         0.4652, 0.4903, 0.4715, 0.4892, 0.5908, 0.5384, 0.5032, 0.5080, 0.4694,
         0.5074, 0.4898, 0.4167, 0.4945, 0.4610, 0.4798, 0.4316, 0.4581, 0.4991,
         0.4965, 0.4673, 0.5108, 0.5224, 0.5675, 0.5273, 0.5143, 0.5684, 0.5113,
         0.5555, 0.4385, 0.4856, 0.5707, 0.4919, 0.5663, 0.4429, 0.5192, 0.5064,
         0.5244, 0.5011, 0.5153, 0.5211, 0.5387, 0.4443, 0.5415, 0.4890, 0.5044,
         0.5348, 0.5245, 0.5401, 0.5299, 0.4814, 0.5381, 0.4514, 0.4638, 0.5091,
         0.5288, 0.4785, 0.5

In [13]:
im_tensor.detach().numpy()

array([[0.48396084, 0.50242853, 0.50757617, 0.4929314 , 0.5117811 ,
        0.5017587 , 0.4754557 , 0.5197366 , 0.53126913, 0.5117519 ,
        0.4899784 , 0.55238974, 0.44322702, 0.4769237 , 0.46068242,
        0.46847698, 0.4042772 , 0.4905003 , 0.47416022, 0.54611826,
        0.5726891 , 0.43630168, 0.47666442, 0.4839468 , 0.49061292,
        0.53868544, 0.45191017, 0.5255328 , 0.50831515, 0.49537763,
        0.52894074, 0.41478947, 0.4634701 , 0.4889504 , 0.46822247,
        0.51879245, 0.54211485, 0.5007308 , 0.5282778 , 0.46580112,
        0.49774894, 0.53363276, 0.49008328, 0.5217825 , 0.5263531 ,
        0.43761384, 0.5242292 , 0.53213936, 0.45141175, 0.5137749 ,
        0.47137958, 0.5223932 , 0.5452998 , 0.4778059 , 0.4652325 ,
        0.49034524, 0.47146654, 0.4891581 , 0.5908044 , 0.53842264,
        0.5031902 , 0.50798064, 0.46944162, 0.50740236, 0.4897881 ,
        0.41672307, 0.49453205, 0.461012  , 0.47983873, 0.43160218,
        0.45814124, 0.49911287, 0.49651286, 0.46

In [14]:
new_im_np = im_tensor.detach().numpy()
new_im_np

array([[0.48396084, 0.50242853, 0.50757617, 0.4929314 , 0.5117811 ,
        0.5017587 , 0.4754557 , 0.5197366 , 0.53126913, 0.5117519 ,
        0.4899784 , 0.55238974, 0.44322702, 0.4769237 , 0.46068242,
        0.46847698, 0.4042772 , 0.4905003 , 0.47416022, 0.54611826,
        0.5726891 , 0.43630168, 0.47666442, 0.4839468 , 0.49061292,
        0.53868544, 0.45191017, 0.5255328 , 0.50831515, 0.49537763,
        0.52894074, 0.41478947, 0.4634701 , 0.4889504 , 0.46822247,
        0.51879245, 0.54211485, 0.5007308 , 0.5282778 , 0.46580112,
        0.49774894, 0.53363276, 0.49008328, 0.5217825 , 0.5263531 ,
        0.43761384, 0.5242292 , 0.53213936, 0.45141175, 0.5137749 ,
        0.47137958, 0.5223932 , 0.5452998 , 0.4778059 , 0.4652325 ,
        0.49034524, 0.47146654, 0.4891581 , 0.5908044 , 0.53842264,
        0.5031902 , 0.50798064, 0.46944162, 0.50740236, 0.4897881 ,
        0.41672307, 0.49453205, 0.461012  , 0.47983873, 0.43160218,
        0.45814124, 0.49911287, 0.49651286, 0.46

In [15]:
new_im_raw = (new_im_np * 255).clip(0, 255).astype(np.uint8).reshape((16, 16))
new_im_raw

array([[123, 128, 129, 125, 130, 127, 121, 132, 135, 130, 124, 140, 113,
        121, 117, 119],
       [103, 125, 120, 139, 146, 111, 121, 123, 125, 137, 115, 134, 129,
        126, 134, 105],
       [118, 124, 119, 132, 138, 127, 134, 118, 126, 136, 124, 133, 134,
        111, 133, 135],
       [115, 131, 120, 133, 139, 121, 118, 125, 120, 124, 150, 137, 128,
        129, 119, 129],
       [124, 106, 126, 117, 122, 110, 116, 127, 126, 119, 130, 133, 144,
        134, 131, 144],
       [130, 141, 111, 123, 145, 125, 144, 112, 132, 129, 133, 127, 131,
        132, 137, 113],
       [138, 124, 128, 136, 133, 137, 135, 122, 137, 115, 118, 129, 134,
        122, 130, 127],
       [129, 133, 124, 114, 137, 120, 122, 136, 127, 134, 113, 126, 130,
        114, 130, 116],
       [126, 116, 130, 109, 135, 129, 129, 111, 125, 126, 129, 123, 135,
        140, 127, 127],
       [115, 120, 143, 118, 140, 129, 121, 124, 119, 135, 116, 134, 129,
        142, 121, 130],
       [137, 125, 120, 124, 12

In [16]:
new_im = Image.fromarray(new_im_raw)
display(new_im)

In [17]:
# cls_weights = torch.Tensor(np.asarray([0.01, 0.49, 0.01, 0.49, 0.01]))
# cls_weights = torch.Tensor(np.asarray([0.001, 0.001, 0.001, 0.996, 0.001]))
# cls_weights = torch.Tensor(np.asarray([1, 1, 1, 1, 1]))
# loss = nn.CrossEntropyLoss(weight=cls_weights)

In [33]:
def step_image(im_np, label=0, lr=100, debug=True):
    im_tensor = torch.Tensor(im_np)
    im_tensor.requires_grad = True
    im_tensor.grad = None
    model.zero_grad()
    preds = model(im_tensor)
    if debug:
        print(preds)
    target = torch.empty([1], dtype=torch.long)
    target[0] = label
    loss = nn.CrossEntropyLoss()
    output = loss(preds, target)
    if debug:
        print(output)
    output.backward()
    new_im_tensor = im_tensor - im_tensor.grad * lr
    new_im_np = new_im_tensor.detach().numpy().clip(0, 1)
    
    if debug:
        new_im_raw = (new_im_np * 255).astype(np.uint8).reshape((16, 16))
        new_im = Image.fromarray(new_im_raw)
        display(new_im)
    return new_im_np

In [105]:
def generate_adversarial(LABEL, prefix='', debug=True):
    im_np = np.random.rand(1, 256)
    for i in range(1001):
        im_np = step_image(im_np, label=LABEL, lr=(i / 1000) ** 2 * 1000 + 1, debug=i % 100 == 0 and debug)
        
    new_im_raw = (im_np * 255).astype(np.uint8).reshape((16, 16))
    new_im = Image.fromarray(new_im_raw)
    
    if debug:
        print(np.asarray(new_im) / 255)
    
    if debug:
        print(f'{LABEL}.png')
    new_im.save(f'{prefix}{LABEL}.png')

In [62]:
generate_adversarial(0)

tensor([[0.0497, 0.2014, 0.0635, 0.0497, 0.6358]], grad_fn=<SoftmaxBackward>)
tensor(1.7875, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.3608, 0.0543, 0.0543, 0.4764]], grad_fn=<SoftmaxBackward>)
tensor(1.7722, grad_fn=<NllLossBackward>)


tensor([[0.7528, 0.0618, 0.0618, 0.0618, 0.0618]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


tensor([[0.7528, 0.0618, 0.0618, 0.0618, 0.0618]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


tensor([[0.7528, 0.0618, 0.0618, 0.0618, 0.0618]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


0.png


In [56]:
generate_adversarial(1)

tensor([[0.0480, 0.2982, 0.0719, 0.0480, 0.5339]], grad_fn=<SoftmaxBackward>)
tensor(1.5305, grad_fn=<NllLossBackward>)


tensor([[0.0618, 0.7528, 0.0618, 0.0618, 0.0618]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


tensor([[0.0618, 0.7528, 0.0618, 0.0618, 0.0618]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


tensor([[0.0618, 0.7528, 0.0618, 0.0618, 0.0618]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


tensor([[0.0618, 0.7528, 0.0618, 0.0618, 0.0618]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


1.png


In [41]:
generate_adversarial(2)

tensor([[0.0536, 0.1602, 0.0536, 0.0536, 0.6789]], grad_fn=<SoftmaxBackward>)
tensor(1.7886, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.4185, 0.0543, 0.0543, 0.4185]], grad_fn=<SoftmaxBackward>)
tensor(1.7713, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.3717, 0.0543, 0.0543, 0.4654]], grad_fn=<SoftmaxBackward>)
tensor(1.7719, grad_fn=<NllLossBackward>)


tensor([[0.0542, 0.4965, 0.0542, 0.0542, 0.3409]], grad_fn=<SoftmaxBackward>)
tensor(1.7730, grad_fn=<NllLossBackward>)


tensor([[0.0618, 0.0618, 0.7528, 0.0618, 0.0618]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


2.png


In [55]:
generate_adversarial(3)

tensor([[0.0481, 0.0695, 0.1656, 0.0481, 0.6687]], grad_fn=<SoftmaxBackward>)
tensor(1.7928, grad_fn=<NllLossBackward>)


tensor([[0.0496, 0.0649, 0.2669, 0.0496, 0.5690]], grad_fn=<SoftmaxBackward>)
tensor(1.7816, grad_fn=<NllLossBackward>)


tensor([[0.0761, 0.0527, 0.0746, 0.7438, 0.0527]], grad_fn=<SoftmaxBackward>)
tensor(1.1076, grad_fn=<NllLossBackward>)


tensor([[0.0618, 0.0618, 0.0618, 0.7528, 0.0618]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


tensor([[0.0618, 0.0618, 0.0618, 0.7528, 0.0618]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


3.png


In [57]:
generate_adversarial(4)

tensor([[0.0538, 0.1483, 0.0538, 0.0538, 0.6904]], grad_fn=<SoftmaxBackward>)
tensor(1.1534, grad_fn=<NllLossBackward>)


tensor([[0.0618, 0.0618, 0.0618, 0.0618, 0.7528]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


tensor([[0.0618, 0.0618, 0.0618, 0.0618, 0.7528]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


tensor([[0.0618, 0.0618, 0.0618, 0.0618, 0.7528]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


tensor([[0.0618, 0.0618, 0.0618, 0.0618, 0.7528]], grad_fn=<SoftmaxBackward>)
tensor(1.1000, grad_fn=<NllLossBackward>)


4.png


In [72]:
!rm test/label0/*

In [108]:
generate_adversarial(0, prefix=f'test/label0/', debug=True)

tensor([[0.0513, 0.1509, 0.0593, 0.0513, 0.6871]], grad_fn=<SoftmaxBackward>)
tensor(1.7919, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.4185, 0.0543, 0.0543, 0.4185]], grad_fn=<SoftmaxBackward>)
tensor(1.7713, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.4185, 0.0543, 0.0543, 0.4185]], grad_fn=<SoftmaxBackward>)
tensor(1.7713, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.4185, 0.0543, 0.0543, 0.4185]], grad_fn=<SoftmaxBackward>)
tensor(1.7713, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.4185, 0.0543, 0.0543, 0.4185]], grad_fn=<SoftmaxBackward>)
tensor(1.7713, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.4185, 0.0543, 0.0543, 0.4185]], grad_fn=<SoftmaxBackward>)
tensor(1.7713, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.4185, 0.0543, 0.0543, 0.4185]], grad_fn=<SoftmaxBackward>)
tensor(1.7713, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.4185, 0.0543, 0.0543, 0.4185]], grad_fn=<SoftmaxBackward>)
tensor(1.7713, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.4185, 0.0543, 0.0543, 0.4185]], grad_fn=<SoftmaxBackward>)
tensor(1.7713, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.4185, 0.0543, 0.0543, 0.4185]], grad_fn=<SoftmaxBackward>)
tensor(1.7713, grad_fn=<NllLossBackward>)


tensor([[0.0543, 0.4185, 0.0543, 0.0543, 0.4185]], grad_fn=<SoftmaxBackward>)
tensor(1.7713, grad_fn=<NllLossBackward>)


[[0.91372549 0.70980392 0.09019608 0.03921569 0.18823529 0.69019608
  0.19607843 0.74509804 0.99607843 0.94117647 0.71372549 0.59215686
  0.25882353 0.68235294 0.38039216 0.78823529]
 [0.64313725 0.56078431 0.32941176 0.98823529 0.67058824 0.
  0.61568627 0.16862745 0.4745098  0.59215686 0.8745098  0.38823529
  0.22352941 0.4627451  0.57254902 0.09411765]
 [0.11764706 1.         0.31764706 0.57254902 0.02745098 0.57254902
  0.18039216 0.39607843 0.39607843 0.91372549 1.         0.64313725
  0.41960784 0.22745098 0.43137255 0.69019608]
 [0.50980392 0.70980392 0.16862745 0.79215686 0.73333333 0.17647059
  0.         0.57254902 0.11764706 0.99607843 0.44705882 0.16078431
  0.00392157 0.25882353 0.75686275 0.5254902 ]
 [0.76862745 0.64313725 0.12156863 0.87058824 0.43921569 0.83529412
  0.         0.1254902  0.14901961 0.65098039 0.99215686 0.38039216
  0.53333333 0.94509804 0.29019608 0.93333333]
 [0.6        0.87843137 0.         0.12156863 0.62352941 0.96078431
  0.4745098  0.         0

In [109]:
import subprocess

In [116]:
while True:
    generate_adversarial(0, prefix=f'test/label0/', debug=False)
    output = subprocess.check_output(["python3", "eval.py", "./test/"]).decode().split('\n')[2].strip()
    print(output)
    if output == '0':
        break

1
1
1
1
1
4
1
1
3
1
4
1
1
4
1
4
1
2
1
1
1
4
1
1
1
1
1
1
1
4
1
1
4
2
1
1
1
1
1
4
1
1
1
1
1
4
1
1
1
1
1
1
1
1
1
1
1
4
1
1
1
1
1
4
1
2
1
1
1
1
1
1
4
1
4
1
1
1
1
1
1
4
1
4
1
1
1
1
1
1
1
1
4
1
1
1
1
4
1
4
1
1
1
4
4
1
1
1
4
1
1
1
1
1
4
1
1
1
1
1
1
1
1
1
4
1
1
1
1
1
4
1
1
1
1
4
4
4
1
1
1
2
1
1
1
1
4
1
1
1
1
1
4
4
1
2
4
1
1
1
1
4
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
4
1
1
1
1
2
1
4
1
1
1
1
1
4
1
1
1
1
1
4
1
1
1
1
1
1
4
4
1
4
1
1
1
1
1
1
1
1
1
1
4
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
3
4
1
4
4
1
1
1
4
4
4
4
1
1
1
1
4
1
1
1
4
1
1
1
4
1
1
1
1
2
4
4
1
1
1
1
1
1
1
1
1
1
4
1
2
1
1
1
4
1
1
1
1
4
1
1
1
1
4
4
1
1
2
2
1
1
1
1
1
1
1
1
4
1
4
1
4
1
1
1
1
1
1
4
4
1
1
1
1
1
1
1
1
1
1
1
4
1
0


In [89]:
def step_even_image(im_np, lr=100, debug=True):
    im_tensor = torch.Tensor(im_np)
    im_tensor.requires_grad = True
    im_tensor.grad = None
    model.zero_grad()
    preds = model(im_tensor)
    if debug:
        print(preds)
        
    for label in range(5):
        target = torch.empty([1], dtype=torch.long)
        target[0] = label
        loss = nn.CrossEntropyLoss()
        output = loss(preds, target)
#         if debug:
#             print(output)
    output.backward()
    new_im_tensor = im_tensor - im_tensor.grad * 0.2 * lr 
    new_im_np = new_im_tensor.detach().numpy().clip(0, 1)
    
    if debug:
        new_im_raw = (new_im_np * 255).astype(np.uint8).reshape((16, 16))
        new_im = Image.fromarray(new_im_raw)
        display(new_im)
    return new_im_np

In [94]:
def generate_even_adversarial(prefix=''):
    im_np = np.random.rand(1, 256)
    for i in range(101):
        im_np = step_even_image(im_np, lr=(i / 100) ** 2 * 1000 + 1, debug=i % 25 == 0)
        
    new_im_raw = (im_np * 255).astype(np.uint8).reshape((16, 16))
    new_im = Image.fromarray(new_im_raw)
    
#     print(np.asarray(new_im) / 255)
    new_im.save(f'{prefix}hoboy.png')

In [95]:
generate_even_adversarial(prefix=f'even/label0/')

tensor([[0.0430, 0.1241, 0.6583, 0.0430, 0.1316]], grad_fn=<SoftmaxBackward>)


tensor([[0.0618, 0.0618, 0.0618, 0.0618, 0.7528]], grad_fn=<SoftmaxBackward>)


tensor([[0.0618, 0.0618, 0.0618, 0.0618, 0.7528]], grad_fn=<SoftmaxBackward>)


tensor([[0.0618, 0.0618, 0.0618, 0.0618, 0.7528]], grad_fn=<SoftmaxBackward>)


tensor([[0.0618, 0.0618, 0.0618, 0.0618, 0.7528]], grad_fn=<SoftmaxBackward>)
